name: flutter_constraintlayout
description: Build flexible layouts with constraints, Similar to Android ConstraintLayout.
version: 0.9.5-stable
anthor: hackware
homepage: https://github.com/hackware1993/Flutter-ConstraintLayout

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/test.png
    - assets/test2.png