name: flutter_constraintlayout
description: Build flexible layouts with constraints, Similar to Android ConstraintLayout.
version: 0.9.10-stable
anthor: hackware
homepage: https://github.com/hackware1993/Flutter-ConstraintLayout

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/test.webp
    - assets/test2.webp
    - assets/icon_back.webp
    - example/badge.dart
    - example/barrier.dart
    - example/complex_list.dart
    - example/guideline.dart
    - example/preprocess_complex_list.dart
    - example/summary.dart